### ISSUE TITLE
Question about using SEED dataset

### ISSUE THREAD

**Issue by comojin1994** [eeyhsong/EEG-Conformer#1]
Hi,

I'm impressed with your paper.

After reading the paper, I got some questions about using and evaluating the SEED dataset.

In the paper, you mentioned that each session contains 3394 trials, segmented from the original data using a non-overlapped one-second time window. However, I want to know more details about dataset settings.

### Q2. The number of subjects is 15, with three sessions for each subject. In addition, each session consists of 15 clips. If you follow the train&test setting in Zheng et al., Did you also split the train set as the first 9 data and the test set as the last 6 data? If this is not the case, could you explain more about this?

```
W.-L. Zheng and B.-L. Lu, "Investigating critical frequency bands and channels for EEG-based emotion recognition with deep neural networks," IEEE Transactions on autonomous mental development, Vol. 7, No. 3, 2015, pp. 162-175.
```

### Q4. If it's alright with you, could you share your preprocessing code about the SEED dataset?

Thank you for sharing your excellent research.

**Comment by eeyhsong** [comment]
Hello @ @comojin1994,
sorry for the late reply.
1. Yes the input uses one-second data with a sample rate of 200 Hz.
2. I use 5-fold cross-validation for SEED dataset [1], instead of a 9:6 manner. Both of the two evaluation ways are widely used for this dataset. The 15 sessions of SEED were stimulated with different movie clips, and I think there may be more significant differences in the emotion produced by different sessions. 
> [1] Zheng, Wei-Long, Jia-Yi Zhu, and Bao-Liang Lu. "Identifying stable patterns over time for emotion recognition from EEG." IEEE Transactions on Affective Computing 10.3 (2017): 417-429.
3. Yes, I averaged the results of 45 sessions to get the final results.
4. I will organize the code and release it later. 
5. I think it is of interest to use this way of connecting convolution and self-attention to be as a new backbone for EEG analysis.

Best wishes. 🤝

**Comment by 384068026** [comment]
> 谢谢你的回答！！😃

您好，我的研究方向是脑电信号情绪识别，您提到的SEED系列数据集我先前也进行过大量试验，关于本项目作者的另一个项目EEG-Transformer项目我也有所研究，针对您的问题，我似乎有解决方案，但是想与您沟通一下，如您同意，请添加我的QQ：384068026

**Comment by 384068026** [comment]
> 谢谢你的回答！！😃

您好，我的研究方向是脑电信号情绪识别，您提到的SEED系列数据集我先前也进行过大量试验，关于本项目作者的另一个项目EEG-Transformer项目我也有所研究，针对您的问题，我有意更改相关代码并编写一个将SEED系列代码从原始数据处理到类似EEG-Transformer所需数据的结构的代码，但是想与您沟通一下，如您同意，请添加我的QQ：384068026
